// src/app/lib/constants.ts

// Generates [ "2026", "2025", "2024", ..., "1980" ]
export const SHIRT_YEARS = Array.from(
  { length: 2026 - 1980 + 1 },
  (_, i) => (2026 - i).toString()
);

export const SHIRT_CONDITIONS = [8, 9, 10] as const;

export const SHIRT_SIZES = [
  'YS', 'YM', 'YL', 'YXL',
  'XS', 'S', 'M', 'L', 'XL', '2XL', '3XL', '4XL', '5XL', '6XL'
] as const;

export const KIT_TYPES = [
  'Home', 'Away', 'Third', 'Fourth', 'Fifth', 
  'GK', 'Jacket', 'Drill', 'Polo', 'Pre-match'
] as const;

export const KIT_SPECS = ['Stadium', 'Player Issue'] as const;

// Top Featured Brands
export const POPULAR_BRANDS = [
  'Nike',
  'Adidas',
  'Puma',
  'Umbro',
  'Kappa',
] as const;

// All Brands (A–Z)
export const KIT_BRANDS = [
  'Adidas',
  'Admiral',
  'Asics',
  'Castore',
  'Charly',
  'Diadora',
  'Ennerre (NR)',
  'Erreà',
  'Fila',
  'Hummel',
  'Joma',
  'Kappa',
  'Kelme',
  'Le Coq Sportif',
  'Lotto',
  'Macron',
  'Matchwinner',
  'Mizuno',
  'New Balance',
  'Nike',
  'Other / Unbranded',
  'Pony',
  'Puma',
  'Reebok',
  'Umbro',
  'Under Armour',
] as const;

// Top Featured Clubs
export const POPULAR_TEAMS = [
  'Arsenal',
  'Barcelona',
  'Bayern',
  'Chelsea',
  'Inter Milan',
  'Juventus',
  'Liverpool',
  'Manchester City',
  'Manchester United',
  'PSG',
  'Real Madrid',
  'Tottenham Hotspur',
] as const;

// All Teams & Nations (A–Z)
export const TEAMS_AND_COUNTRIES = [
  'AC Milan',
  'AFC Bournemouth',
  'AS Roma',
  'Abha',
  'Ajax',
  'Al Ahli',
  'Al Ettifaq',
  'Al Fateh',
  'Al Fayha',
  'Al Hazem',
  'Al Hilal',
  'Al Ittihad',
  'Al Khaleej',
  'Al Nassr',
  'Al Okhdood',
  'Al Qadsiah',
  'Al Raed',
  'Al Riyadh',
  'Al Shabab',
  'Al Taawoun',
  'Al Wehda',
  'Albirex Niigata',
  'Algeria',
  'Argentina',
  'Arsenal',
  'Aston Villa',
  'Atalanta',
  'Athletic Bilbao',
  'Atlanta United',
  'Atletico Madrid',
  'Atlético San Luis',
  'Atlas',
  'Australia',
  'Austria',
  'Auxerre',
  'Avispa Fukuoka',
  'Barcelona',
  'Bayern',
  'Beijing Guoan',
  'Belgium',
  'Besiktas',
  'Birmingham',
  'Blackburn Rovers',
  'Boca Juniors',
  'Bologna',
  'Borussia Mönchengladbach',
  'Brazil',
  'Brentford',
  'Brighton & Hove Albion',
  'Burnley',
  'CF Montréal',
  'CSA Steaua București',
  'Cameroon',
  'Canada',
  'Cangzhou Mighty Lions',
  'Celtic',
  'Central Coast Mariners',
  'Cerezo Osaka',
  'Changchun Yatai',
  'Charlotte',
  'Chelsea',
  'Chengdu Rongcheng',
  'Chicago Fire',
  'Chile',
  'China',
  'Chivas USA',
  'Club América',
  'Colombia',
  'Colorado Rapids',
  'Columbus Crew',
  'Costa Rica',
  'Croatia',
  'Cruz Azul',
  'Crystal Palace',
  'Czech Republic',
  'DC United',
  'Damac',
  'Denmark',
  'Dortmund',
  'Ecuador',
  'Egypt',
  'England',
  'Everton',
  'FC Augsburg',
  'FC Cincinnati',
  'FC Dallas',
  'FC Magdeburg',
  'FC Tokyo',
  'Feyenoord',
  'Fiorentina',
  'Flamengo',
  'France',
  'Fulham',
  'Galatasaray',
  'Gamba Osaka',
  'Genoa',
  'Germany',
  'Ghana',
  'Goyang KB Kookmin Bank FC',
  'Guadalajara',
  'Guangzhou Evergrande',
  'Hamburg',
  'Henan',
  'Hokkaido Consadole Sapporo',
  'Holland',
  'Hong Kong',
  'Houston Dynamo',
  'Hull City',
  'Hungary',
  'Inter Miami',
  'Inter Milan',
  'Ipswich Town',
  'Iran',
  'Ireland',
  'Italy',
  'Ivory Coast',
  'Jamaica',
  'Japan',
  'Jeonbuk Hyundai Motors',
  'Juárez',
  'Jubilo Iwata',
  'Juventus',
  'Kaiserslautern',
  'Kashima Antlers',
  'Kashiwa Reysol',
  'Kawasaki Frontale',
  'Kitchee',
  'Kyoto Sanga',
  'LA Galaxy',
  'LAFC',
  'Lazio',
  'Lecce',
  'Leeds United',
  'Leicester City',
  'León',
  'Lille',
  'Liverpool',
  'Lyon',
  'Machida Zelvia',
  'Manchester City',
  'Manchester United',
  'Marseille',
  'Mazatlán',
  'Meizhou Hakka',
  'Melbourne Victory',
  'Mexico',
  'Millonarios',
  'Millwall',
  'Minnesota United',
  'Mizuno',
  'Monterrey',
  'Morocco',
  'Nagoya Grampus',
  'Nantong Zhiyun',
  'Napoli',
  'Nashville SC',
  'Necaxa',
  'New York City FC',
  'New York Cosmos',
  'New York Red Bulls',
  'Newcastle United',
  'Nigeria',
  'Northern Ireland',
  'Norway',
  'Norwich City',
  'Nottingham Forest',
  'Orlando City',
  'Orlando Pirates',
  'PSG',
  'PSV',
  'Pachuca',
  'Paraguay',
  'Parma',
  'Philadelphia Union',
  'Pohang Steelers',
  'Poland',
  'Porto',
  'Portland Timbers',
  'Portugal',
  'Puebla',
  'Pumas UNAM',
  'Qingdao Hainiu',
  'Qingdao West Coast',
  'Qatar',
  'Querétaro',
  'RB Leipzig',
  'Rangers',
  'Rayong FC',
  'Real Madrid',
  'Real Salt Lake',
  'Real Valladolid',
  'Sagan Tosu',
  'San Diego',
  'San Jose Earthquakes',
  'Sanfrecce Hiroshima',
  'Santos Laguna',
  'Saudi Arabia',
  'Scotland',
  'Seattle Sounders',
  'Senegal',
  'Seoul FC',
  'Serbia',
  'Shandong Taishan',
  'Shanghai Port',
  'Shanghai Shenhua',
  'Sheffield Wednesday',
  'Shenzhen Peng City',
  'Shimizu S Pulse',
  'Shonan Bellmare',
  'Singapore',
  'Slovenia',
  'South Africa',
  'South China AA',
  'South Korea',
  'Spain',
  'Sporting Gijon',
  'Sporting Kansas City',
  'St. Louis City',
  'Stoke City',
  'Stuttgarter Kickers',
  'Sunderland',
  'Suning',
  'Suwon Samsung Bluewings',
  'Swansea',
  'Sweden',
  'Swindon Town',
  'Switzerland',
  'Thailand',
  'Tianjin Jinmen Tiger',
  'Tigres UANL',
  'Tijuana',
  'Tokyo Verdy',
  'Toluca',
  'Torino',
  'Toronto FC',
  'Tottenham Hotspur',
  'Tunisia',
  'Turkey',
  'USA',
  'Udinese',
  'Ukraine',
  'Urawa Red Diamonds',
  'Uruguay',
  'Valencia',
  'Vancouver Whitecaps',
  'Vasco De Gama',
  'VfB Stuttgart',
  'VfL Wolfsburg',
  'Vietnam',
  'Villarreal',
  'Vissel Kobe',
  'West Ham United',
  'Wolverhampton Wanderers',
  'Wuhan Three Towns',
  'Yokohama F Marinos',
  'Yugoslavia',
  'Zhejiang',
] as const;