// src/app/lib/seed.ts
import { connectDB } from './db';
import { Product } from '../models/Products';

const sampleKits = [
  {
    title: 'Arsenal 2003/04 Invincibles Home Shirt',
    slug: 'arsenal-2003-04-invincibles-home',
    team: 'Arsenal',
    brand: 'Nike',
    year: '2003',
    condition: 10,
    kitType: 'Home',
    spec: 'Stadium',
    price: 3499,
    images: ['https://images.unsplash.com/photo-1517466787929-bc90951d0974?w=800'],
    variants: [
      { size: 'S', stock: 3 },
      { size: 'M', stock: 8 },
      { size: 'L', stock: 5 },
      { size: 'XL', stock: 2 },
    ],
  },
  {
    title: 'Real Madrid 2017/18 Final Kyiv Away Shirt',
    slug: 'real-madrid-2017-18-final-kyiv-away',
    team: 'Real Madrid',
    brand: 'Adidas',
    year: '2017',
    condition: 9,
    kitType: 'Away',
    spec: 'Player Issue',
    price: 4199,
    images: ['https://images.unsplash.com/photo-1522778119026-d647f0596c20?w=800'],
    variants: [
      { size: 'M', stock: 4 },
      { size: 'L', stock: 6 },
      { size: 'XL', stock: 1 },
    ],
  },
  {
    title: 'Japan 2022 World Cup Home Shirt',
    slug: 'japan-2022-world-cup-home',
    team: 'Japan',
    brand: 'Adidas',
    year: '2022',
    condition: 10,
    kitType: 'Home',
    spec: 'Stadium',
    price: 3899,
    images: ['https://images.unsplash.com/photo-1551972251-12070d63502a?w=800'],
    variants: [
      { size: 'S', stock: 6 },
      { size: 'M', stock: 10 },
      { size: 'L', stock: 7 },
    ],
  },
  {
    title: 'Manchester United 1998/99 Treble Winners Home Shirt',
    slug: 'manchester-united-1998-99-treble-winners-home',
    team: 'Manchester United',
    brand: 'Umbro',
    year: '1998',
    condition: 9,
    kitType: 'Home',
    spec: 'Stadium',
    price: 5499,
    images: ['https://images.unsplash.com/photo-1577223625816-7546f13df25d?w=800'],
    variants: [
      { size: 'M', stock: 2 },
      { size: 'L', stock: 2 },
      { size: 'XL', stock: 1 },
    ],
  },
  {
    title: 'Italy 2006 World Cup Champions Home Shirt',
    slug: 'italy-2006-world-cup-champions-home',
    team: 'Italy',
    brand: 'Puma',
    year: '2006',
    condition: 8,
    kitType: 'Home',
    spec: 'Player Issue',
    price: 3799,
    images: ['https://images.unsplash.com/photo-1518091043644-c1d4457512c6?w=800'],
    variants: [
      { size: 'L', stock: 3 },
      { size: 'XL', stock: 1 },
    ],
  },
  {
    title: 'AC Milan 2006/07 Athens Final Away Shirt',
    slug: 'ac-milan-2006-07-athens-final-away',
    team: 'AC Milan',
    brand: 'Adidas',
    year: '2006',
    condition: 10,
    kitType: 'Away',
    spec: 'Player Issue',
    price: 4999,
    images: ['https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=800'],
    variants: [
      { size: 'S', stock: 2 },
      { size: 'M', stock: 4 },
      { size: 'L', stock: 3 },
    ],
  },
  {
    title: 'Barcelona 2010/11 Wembley UCL Champions Home Shirt',
    slug: 'barcelona-2010-11-wembley-ucl-home',
    team: 'Barcelona',
    brand: 'Nike',
    year: '2010',
    condition: 10,
    kitType: 'Home',
    spec: 'Player Issue',
    price: 4699,
    images: ['https://images.unsplash.com/photo-1511886929837-354d827aae26?w=800'],
    variants: [
      { size: 'S', stock: 4 },
      { size: 'M', stock: 6 },
      { size: 'L', stock: 4 },
    ],
  },
  {
    title: 'France 1998 World Cup Victory Home Shirt',
    slug: 'france-1998-world-cup-victory-home',
    team: 'France',
    brand: 'Adidas',
    year: '1998',
    condition: 9,
    kitType: 'Home',
    spec: 'Stadium',
    price: 5299,
    images: ['https://images.unsplash.com/photo-1543326727-cf6c39e8f84c?w=800'],
    variants: [
      { size: 'M', stock: 2 },
      { size: 'L', stock: 3 },
    ],
  },
  {
    title: 'Juventus 1996/97 Centenario Blue Away Shirt',
    slug: 'juventus-1996-97-centenario-blue-away',
    team: 'Juventus',
    brand: 'Kappa',
    year: '1996',
    condition: 8,
    kitType: 'Away',
    spec: 'Stadium',
    price: 4299,
    images: ['https://images.unsplash.com/photo-1517927033932-b3d18e61fb3a?w=800'],
    variants: [
      { size: 'M', stock: 1 },
      { size: 'L', stock: 2 },
      { size: 'XL', stock: 1 },
    ],
  },
  {
    title: 'Dortmund 1996/97 European Champions Home Shirt',
    slug: 'dortmund-1996-97-european-champions-home',
    team: 'Dortmund',
    brand: 'Nike',
    year: '1996',
    condition: 9,
    kitType: 'Home',
    spec: 'Stadium',
    price: 3999,
    images: ['https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=800'],
    variants: [
      { size: 'S', stock: 3 },
      { size: 'M', stock: 5 },
      { size: 'L', stock: 2 },
    ],
  },
];

export async function seedProducts() {
  await connectDB();
  await Product.deleteMany({});
  const inserted = await Product.insertMany(sampleKits);
  return inserted;
}